export type HoladayCardTheme =
  | 'work'
  | 'relationship'
  | 'emotion'
  | 'space'
  | 'confidence'
  | 'uplift';

export interface HoladayEnergyCard {
  id: string;
  title: string;
  subtitle: string;
  body: string;
  action: string;
  answer: 'yes' | 'no' | 'wait';
  primaryTheme: HoladayCardTheme;
  themes: HoladayCardTheme[];
}

export const HOLADAY_ENERGY_CARDS: HoladayEnergyCard[] = [
  {
    id: 'work-01',
    title: '先推一厘米',
    subtitle: '动量比完整更重要',
    body: '现在不必解决整件事。把最小可交付动作找出来，完成后再决定下一步，让真实进展替你降低压力。',
    action: '用 10 分钟完成最小一步，并留下下一步备注。',
    answer: 'yes',
    primaryTheme: 'work',
    themes: ['work', 'confidence'],
  },
  {
    id: 'work-02',
    title: '关掉一扇窗',
    subtitle: '给注意力留出位置',
    body: '任务没有变难，可能只是入口太多。暂时收起无关页面和消息，把眼前这一段做成一个清楚的完成点。',
    action: '关闭三个无关窗口，专注 12 分钟。',
    answer: 'yes',
    primaryTheme: 'work',
    themes: ['work', 'space'],
  },
  {
    id: 'work-03',
    title: '先问清标准',
    subtitle: '别替别人猜答案',
    body: '如果你反复修改仍不踏实，缺的也许不是努力，而是完成标准。一次具体确认，能省下许多无效消耗。',
    action: '写下一个具体问题，在 5 分钟内发给相关人。',
    answer: 'yes',
    primaryTheme: 'work',
    themes: ['work', 'relationship'],
  },
  {
    id: 'work-04',
    title: '今天先不加码',
    subtitle: '守住已承诺的范围',
    body: '新的想法很诱人，但现在更值得保护的是正在推进的承诺。把额外需求放进候选区，不让它打断主线。',
    action: '用 5 分钟建一个“稍后处理”清单。',
    answer: 'no',
    primaryTheme: 'work',
    themes: ['work', 'space'],
  },
  {
    id: 'work-05',
    title: '把难点说出来',
    subtitle: '清楚表达不是示弱',
    body: '卡住的地方如果一直藏着，会继续占用心力。用事实说明现状、影响和需要的支持，让协作重新流动。',
    action: '用三句话写清现状、影响和需要的帮助。',
    answer: 'yes',
    primaryTheme: 'work',
    themes: ['work', 'relationship', 'confidence'],
  },
  {
    id: 'work-06',
    title: '等一个更好时点',
    subtitle: '暂停也可以是策略',
    body: '这件事目前信息不足，继续硬推只会增加返工。先标记缺失条件，给自己一个明确的复查时间再决定。',
    action: '列出两个缺失条件，并设置明天的复查提醒。',
    answer: 'wait',
    primaryTheme: 'work',
    themes: ['work', 'emotion'],
  },
  {
    id: 'relationship-01',
    title: '把期待说具体',
    subtitle: '让对方知道怎样靠近',
    body: '模糊的失望很难被回应。把“你应该懂”换成一个具体请求，既照顾自己，也给关系留下行动空间。',
    action: '用 5 分钟写下一句不责备的具体请求。',
    answer: 'yes',
    primaryTheme: 'relationship',
    themes: ['relationship', 'confidence'],
  },
  {
    id: 'relationship-02',
    title: '先听完这一段',
    subtitle: '不急着证明谁正确',
    body: '回应之前先确认你真的听见了什么。复述对方的重点，不代表完全同意，只是在减少误解和防御。',
    action: '下一次对话先复述对方一句，再表达自己。',
    answer: 'yes',
    primaryTheme: 'relationship',
    themes: ['relationship', 'emotion'],
  },
  {
    id: 'relationship-03',
    title: '留一点空白',
    subtitle: '关系不需要即时结论',
    body: '双方都在用力时，继续讨论可能只会放大情绪。短暂离开不是冷处理，而是为更清楚的回应腾位置。',
    action: '暂停 10 分钟，回来前只整理自己的感受。',
    answer: 'wait',
    primaryTheme: 'relationship',
    themes: ['relationship', 'space', 'emotion'],
  },
  {
    id: 'relationship-04',
    title: '别替对方负责',
    subtitle: '温柔也需要边界',
    body: '你可以关心，但不必承担对方全部的情绪和选择。把能做的与不能做的分开，关系会更诚实。',
    action: '写下一件你愿意做和一件你不会代做的事。',
    answer: 'no',
    primaryTheme: 'relationship',
    themes: ['relationship', 'confidence'],
  },
  {
    id: 'relationship-05',
    title: '发出轻邀请',
    subtitle: '给连接一个低压力入口',
    body: '不需要准备一场郑重谈话。一个轻松、明确、允许拒绝的小邀请，也能让彼此重新感到靠近。',
    action: '在 3 分钟内发出一个可轻松拒绝的邀请。',
    answer: 'yes',
    primaryTheme: 'relationship',
    themes: ['relationship', 'uplift'],
  },
  {
    id: 'relationship-06',
    title: '先回到事实',
    subtitle: '不要让想象替代确认',
    body: '当你开始推测对方的动机，焦虑会迅速加重。区分已经发生的事实和自己的解释，再决定是否询问。',
    action: '列出两条事实和一条未经确认的猜测。',
    answer: 'wait',
    primaryTheme: 'relationship',
    themes: ['relationship', 'emotion'],
  },
  {
    id: 'emotion-01',
    title: '先为感受命名',
    subtitle: '看见它，才有选择',
    body: '情绪不是命令，也不是错误。准确说出此刻更接近委屈、担心还是疲惫，会让身体先松开一点。',
    action: '用 3 分钟写下“我现在感到……因为……”。',
    answer: 'yes',
    primaryTheme: 'emotion',
    themes: ['emotion', 'confidence'],
  },
  {
    id: 'emotion-02',
    title: '允许今天普通',
    subtitle: '不必每天都闪耀',
    body: '今天的能量也许只够维持，而不是突破。把标准调到可持续的位置，完成基本照顾就已经很不错。',
    action: '删掉一项非必要任务，给自己 10 分钟空档。',
    answer: 'yes',
    primaryTheme: 'emotion',
    themes: ['emotion', 'space'],
  },
  {
    id: 'emotion-03',
    title: '身体先知道',
    subtitle: '从紧绷处开始照顾',
    body: '思绪很乱时，不必立刻想通。观察肩颈、呼吸和胃部，把注意力放回身体，答案会慢慢变清楚。',
    action: '做 8 次缓慢呼吸，同时放松肩膀。',
    answer: 'wait',
    primaryTheme: 'emotion',
    themes: ['emotion', 'space'],
  },
  {
    id: 'emotion-04',
    title: '把内耗写在纸上',
    subtitle: '别让它一直循环播放',
    body: '反复出现的念头需要一个出口。写下来不是为了马上解决，而是把它从脑内循环移到可观察的位置。',
    action: '连续写 7 分钟，不修改也不评价内容。',
    answer: 'yes',
    primaryTheme: 'emotion',
    themes: ['emotion', 'space'],
  },
  {
    id: 'emotion-05',
    title: '今天不做重决定',
    subtitle: '高波动时先保护自己',
    body: '强烈情绪会把选择压缩成非黑即白。除非事情紧急，先让波峰过去，再用完整的信息做决定。',
    action: '把决定延后 12 小时，并记下要补充的信息。',
    answer: 'no',
    primaryTheme: 'emotion',
    themes: ['emotion', 'work'],
  },
  {
    id: 'emotion-06',
    title: '找一个安全听众',
    subtitle: '你不必独自消化',
    body: '有些重量在被理解后就会变轻。选择一个不会急着评判的人，说明你现在只需要倾听或具体建议。',
    action: '发一条消息，明确说出你需要倾听还是建议。',
    answer: 'yes',
    primaryTheme: 'emotion',
    themes: ['emotion', 'relationship'],
  },
  {
    id: 'space-01',
    title: '清出一小块桌面',
    subtitle: '让视线先安静下来',
    body: '环境里的杂乱会不断提醒你还有许多事没做。只整理眼前一小块区域，也能给大脑一个完成信号。',
    action: '计时 8 分钟，只整理手边一个区域。',
    answer: 'yes',
    primaryTheme: 'space',
    themes: ['space', 'work'],
  },
  {
    id: 'space-02',
    title: '给消息设一道门',
    subtitle: '不是每个提醒都要进来',
    body: '持续弹出的通知会切碎恢复感。暂时静音并不等于失联，而是在保护一段可以完整呼吸的时间。',
    action: '开启 15 分钟勿扰，只保留紧急联系人。',
    answer: 'yes',
    primaryTheme: 'space',
    themes: ['space', 'emotion'],
  },
  {
    id: 'space-03',
    title: '换一个位置',
    subtitle: '身体移动会带来新视角',
    body: '当思绪和座位一起僵住时，短暂换个场景会改变注意力。你不必远行，只要打断原来的循环。',
    action: '带一杯水走到另一个位置待 10 分钟。',
    answer: 'yes',
    primaryTheme: 'space',
    themes: ['space', 'uplift'],
  },
  {
    id: 'space-04',
    title: '把空档留空',
    subtitle: '别急着填满每一分钟',
    body: '真正的恢复常发生在没有安排的缝隙里。先别用新内容占满它，让注意力自然落回自己身上。',
    action: '留出 10 分钟，不看屏幕也不安排任务。',
    answer: 'no',
    primaryTheme: 'space',
    themes: ['space', 'emotion'],
  },
  {
    id: 'space-05',
    title: '结束一个开放循环',
    subtitle: '让大脑少记一件事',
    body: '未完成的小事会持续占用后台注意力。挑一件五分钟内能关闭的循环，完成、删除或明确延期。',
    action: '在 5 分钟内完成或删除一件小待办。',
    answer: 'yes',
    primaryTheme: 'space',
    themes: ['space', 'work'],
  },
  {
    id: 'space-06',
    title: '先别带回家',
    subtitle: '给一天画出边界',
    body: '有些问题今天已经得不到更好答案。把当前进度和明天第一步写清楚，让大脑得到暂时下班的许可。',
    action: '用 5 分钟写下进度和明天第一步。',
    answer: 'wait',
    primaryTheme: 'space',
    themes: ['space', 'work', 'emotion'],
  },
  {
    id: 'confidence-01',
    title: '证据比怀疑可靠',
    subtitle: '回看你已经做到的事',
    body: '不确定感会放大缺口，却忽略已有能力。找出一个真实完成的例子，让判断重新建立在证据上。',
    action: '写下三件最近完成的小事，限时 5 分钟。',
    answer: 'yes',
    primaryTheme: 'confidence',
    themes: ['confidence', 'work'],
  },
  {
    id: 'confidence-02',
    title: '用自己的语气说',
    subtitle: '不用模仿强势的人',
    body: '有力量不等于声音最大。用你熟悉、清楚而坚定的方式表达立场，反而更容易持续和被理解。',
    action: '把一句犹豫表达改写成清楚陈述并读一遍。',
    answer: 'yes',
    primaryTheme: 'confidence',
    themes: ['confidence', 'relationship'],
  },
  {
    id: 'confidence-03',
    title: '先做一个小曝光',
    subtitle: '让作品离开草稿箱',
    body: '等待完全准备好，会让反馈永远缺席。选择一个低风险对象展示半成品，用真实回应替代想象中的评判。',
    action: '在 10 分钟内把草稿发给一个可信的人。',
    answer: 'yes',
    primaryTheme: 'confidence',
    themes: ['confidence', 'work'],
  },
  {
    id: 'confidence-04',
    title: '拒绝一次过度证明',
    subtitle: '你不需要赢得所有认可',
    body: '当你想解释得更多时，先问这是否真的必要。清楚边界比反复证明更能保护你的时间和自尊。',
    action: '删掉一段多余解释，只保留事实和决定。',
    answer: 'no',
    primaryTheme: 'confidence',
    themes: ['confidence', 'space'],
  },
  {
    id: 'confidence-05',
    title: '允许自己是新手',
    subtitle: '生疏不等于不适合',
    body: '刚开始时动作笨拙很正常。把目标从表现优秀改成收集一次经验，你会更容易迈出真实的一步。',
    action: '做 12 分钟新手练习，只记录一个发现。',
    answer: 'yes',
    primaryTheme: 'confidence',
    themes: ['confidence', 'uplift'],
  },
  {
    id: 'confidence-06',
    title: '先等身体跟上',
    subtitle: '勇敢也需要准备时间',
    body: '你已经知道想往哪里走，只是身体还在适应变化。给自己一点预演和缓冲，不必用仓促证明决心。',
    action: '花 10 分钟预演第一步，并写下最担心的点。',
    answer: 'wait',
    primaryTheme: 'confidence',
    themes: ['confidence', 'emotion'],
  },
  {
    id: 'uplift-01',
    title: '给今天加一点颜色',
    subtitle: '微小愉悦也算补给',
    body: '情绪不一定需要宏大改变。选择一个你喜欢的颜色、声音或味道，让感官收到“现在安全”的信号。',
    action: '用 5 分钟换一张桌面图或播放一首喜欢的歌。',
    answer: 'yes',
    primaryTheme: 'uplift',
    themes: ['uplift', 'space'],
  },
  {
    id: 'uplift-02',
    title: '庆祝一个小完成',
    subtitle: '别让进步悄悄路过',
    body: '如果每个完成都立刻被下个任务覆盖，大脑很难感到前进。停一下，给这个小结果一个明确回应。',
    action: '用 3 分钟记录完成内容，并给自己一个小奖励。',
    answer: 'yes',
    primaryTheme: 'uplift',
    themes: ['uplift', 'work'],
  },
  {
    id: 'uplift-03',
    title: '把好奇心放出来',
    subtitle: '不为产出探索一次',
    body: '一直以结果为目标，会让轻松感逐渐消失。允许自己短暂追随一个无用但有趣的问题，重新找回活力。',
    action: '花 10 分钟了解一个纯粹好奇的小主题。',
    answer: 'yes',
    primaryTheme: 'uplift',
    themes: ['uplift', 'confidence'],
  },
  {
    id: 'uplift-04',
    title: '向光亮处走几步',
    subtitle: '让身体接触真实世界',
    body: '长时间停在屏幕前会让时间变平。走到窗边或户外，看一会真实光线和远处，让注意力重新展开。',
    action: '离开屏幕 8 分钟，走到有自然光的位置。',
    answer: 'yes',
    primaryTheme: 'uplift',
    themes: ['uplift', 'space'],
  },
  {
    id: 'uplift-05',
    title: '今天不追赶快乐',
    subtitle: '轻松不能被强迫',
    body: '越要求自己马上开心，越容易感到失败。先允许平淡和疲惫存在，舒服会在压力减少后慢慢回来。',
    action: '静坐 5 分钟，只观察呼吸，不要求改变情绪。',
    answer: 'no',
    primaryTheme: 'uplift',
    themes: ['uplift', 'emotion'],
  },
  {
    id: 'uplift-06',
    title: '分享一点好消息',
    subtitle: '让喜悦被看见',
    body: '一件小好事在说出来后会更有重量。找一个愿意接住你的人，分享今天一个值得微笑的瞬间。',
    action: '在 3 分钟内发出一条小好事分享。',
    answer: 'yes',
    primaryTheme: 'uplift',
    themes: ['uplift', 'relationship'],
  },
];
