import type { DataCategoryDefinition, SourceEvidence } from './types.js';

function source(path: string, fact: string): SourceEvidence {
  return { kind: 'source_file', path, fact };
}

export const dataCategories: readonly DataCategoryDefinition[] = [
  {
    id: 'account_security',
    displayName: '账号与安全',
    description: '用于注册、登录、身份确认与账号安全的数据。',
    dataElements: ['邮箱', '手机号', '昵称', '头像', '密码哈希', 'MFA 与登录会话'],
    sources: ['用户注册与资料设置', '登录、认证与安全流程'],
    purposes: ['注册、登录、身份确认与账号安全'],
    sensitivity: 'sensitive',
    storageLocations: ['HOLA DAY 账号与会话数据库'],
    processorIds: ['holaday_internal', 'google', 'resend', 'sms_gateway', 'vultr', 'aliyun'],
    retentionPolicyId: 'account_purpose_bound',
    rightsCapabilityId: 'account_manual_request',
    evidence: [
      source('apps/orchestrator/src/db/schema/users.ts', '用户账号资料由 users 表定义。'),
      source('apps/orchestrator/src/db/schema/sessions.ts', '登录会话由 sessions 表定义。'),
      source(
        'apps/orchestrator/src/db/schema/user-mfa-recovery-codes.ts',
        '多因素认证恢复码由专用表定义。',
      ),
    ],
  },
  {
    id: 'task_execution',
    displayName: '任务与执行',
    description: '为执行、恢复和验证用户提交任务所处理的数据。',
    dataElements: ['指令', '计划', '步骤', '结果', '错误', '截图', '网页上下文', '文件'],
    sources: ['用户提交的任务指令与文件', '任务执行过程'],
    purposes: ['执行、恢复和验证您提交的任务'],
    sensitivity: 'sensitive',
    storageLocations: ['HOLA DAY 任务数据库', 'HOLA DAY 任务文件存储'],
    processorIds: [
      'holaday_internal',
      'anthropic',
      'openai',
      'google',
      'dashscope',
      'fal_ai',
      'firecrawl',
      'apify',
      'zapier',
      'vultr',
      'cloudflare_r2',
    ],
    retentionPolicyId: 'task_visibility_unified_unknown',
    rightsCapabilityId: 'task_manual_request',
    evidence: [
      source('apps/orchestrator/src/db/schema/tasks.ts', '任务记录由 tasks 表定义。'),
      source('apps/orchestrator/src/db/schema/task-files.ts', '任务文件记录由 task-files 表定义。'),
      source('apps/orchestrator/src/db/schema/task-steps.ts', '任务执行步骤由 task-steps 表定义。'),
    ],
  },
  {
    id: 'cross_task_memory',
    displayName: '跨任务 AI 记忆',
    description: '从已完成任务摘要提取并用于后续相关任务的上下文。',
    dataElements: ['偏好', '网站状态', '任务历史', '执行建议'],
    sources: ['已完成任务的任务指令与结果摘要'],
    purposes: ['在后续相关任务中提供个性化上下文'],
    sensitivity: 'sensitive',
    storageLocations: ['HOLA DAY 执行记忆存储'],
    processorIds: ['holaday_internal', 'anthropic'],
    retentionPolicyId: 'memory_entry_lifecycle',
    rightsCapabilityId: 'memory_self_service',
    evidence: [
      source('apps/orchestrator/src/db/schema/execution-memory.ts', '执行记忆条目由专用表定义。'),
      source(
        'apps/orchestrator/src/agent/supercar/memory-service.ts',
        '记忆服务处理跨任务记忆条目。',
      ),
      source('apps/orchestrator/src/trpc/routers/memory.ts', '记忆路由提供记忆访问与控制。'),
    ],
  },
  {
    id: 'energy_astrology_profile',
    displayName: '今日能量星座资料',
    description: '用于计算星座并生成个性化能量提示的资料。',
    dataElements: ['姓名', '精确生日', '可选出生时间与地点', '星座', '浏览器时区'],
    sources: ['用户主动填写', '浏览器时区'],
    purposes: ['计算星座并生成个性化的日、周、月、年提示'],
    sensitivity: 'highly_sensitive',
    storageLocations: ['当前浏览器 localStorage', 'HOLA DAY 星座服务请求处理'],
    processorIds: ['holaday_internal', 'divineapi'],
    retentionPolicyId: 'browser_local_until_clear',
    rightsCapabilityId: 'astrology_local_self_service',
    evidence: [
      source('apps/web-workbench/src/lib/astrology.ts', '星座资料在浏览器本地处理与清除。'),
      source('apps/orchestrator/src/astrology/service.ts', '星座服务处理实时星座请求。'),
    ],
  },
  {
    id: 'stock_preference_profile',
    displayName: '股票偏好画像',
    description: '从选股、研究偏好和自选股中归纳的研究偏好资料。',
    dataElements: [
      '成功选股后自动记录的筛选条件',
      '主动设置的研究偏好',
      '新增自选股的股票代码、市场和添加时间',
      '偏好事实、可能优势与潜在盲点',
    ],
    sources: ['成功选股', '用户设置研究偏好', '用户新增自选股'],
    purposes: ['帮助您看见研究重点和可能遗漏的维度；画像不会自动改变筛选条件或触发交易'],
    sensitivity: 'sensitive',
    storageLocations: ['HOLA DAY 股票偏好画像存储'],
    processorIds: ['holaday_internal'],
    retentionPolicyId: 'stock_profile_mixed',
    rightsCapabilityId: 'stock_profile_self_service',
    evidence: [
      source(
        'apps/orchestrator/src/stocks/stock-preference-profile.ts',
        '股票偏好画像定义筛选依据和归纳结果。',
      ),
      source(
        'apps/orchestrator/src/stocks/stock-preference-repository.ts',
        '股票偏好资料由专用仓储读写。',
      ),
    ],
  },
  {
    id: 'feedback_support',
    displayName: '反馈与支持',
    description: '用户主动提交以接收反馈、定位问题并提供支持的数据。',
    dataElements: ['自由文本', '账号邮箱', '账号标识', 'User-Agent', '可选的关联任务标识'],
    sources: ['用户主动提交反馈'],
    purposes: ['接收反馈、定位问题并提供支持'],
    sensitivity: 'sensitive',
    storageLocations: ['HOLA DAY 反馈与服务日志存储'],
    processorIds: ['holaday_internal', 'resend'],
    retentionPolicyId: 'feedback_purpose_bound',
    rightsCapabilityId: 'feedback_manual_request',
    evidence: [
      source('apps/orchestrator/src/trpc/routers/feedback.ts', '反馈路由接收用户反馈内容。'),
    ],
  },
  {
    id: 'external_notifications',
    displayName: '外部通知渠道',
    description: '用户配置的外部渠道及其通知内容。',
    dataElements: [
      '企业微信、飞书、钉钉或自定义 webhook 地址和模板',
      '通知标题、正文、状态',
      '最多 60 字的定时任务意图',
    ],
    sources: ['用户保存的外部通知渠道配置', '已启用渠道发送的通知'],
    purposes: ['向您配置的外部渠道发送任务通知'],
    sensitivity: 'sensitive',
    storageLocations: ['HOLA DAY 通知渠道配置与发送记录'],
    processorIds: ['holaday_internal', 'wecom', 'feishu', 'dingtalk', 'custom_webhook'],
    retentionPolicyId: 'notification_config_until_change',
    rightsCapabilityId: 'notification_self_service',
    evidence: [
      source(
        'apps/orchestrator/src/notifications/notification-service.ts',
        '通知服务向用户配置的外部渠道发送任务通知。',
      ),
      source(
        'apps/orchestrator/src/notifications/scheduled-copy.ts',
        '定时任务通知文案保留受限意图摘要。',
      ),
    ],
  },
  {
    id: 'extension_site_stats',
    displayName: '扩展常用网站',
    description: '设备端汇总后用于准备常用站点配置的域名级统计。',
    dataElements: ['最近 30 天访问记录汇总后的域名', '访问次数', '最近访问时间'],
    sources: ['设备端汇总的最近 30 天访问记录'],
    purposes: ['优先准备常用站点配置'],
    sensitivity: 'sensitive',
    storageLocations: ['HOLA DAY 扩展网站统计快照'],
    processorIds: ['holaday_internal'],
    retentionPolicyId: 'domain_snapshot_replace',
    rightsCapabilityId: 'extension_stats_manual_request',
    evidence: [
      source(
        'apps/orchestrator/src/browsing-history/service.ts',
        '浏览历史服务处理域名级统计快照。',
      ),
      source('apps/extension/src/background/history-sync.ts', '扩展同步设备端域名级聚合。'),
    ],
  },
  {
    id: 'extension_login_cookies',
    displayName: '扩展登录态',
    description: '固定同步域名清单内、用于任务浏览器继承登录状态的真实 Cookie。',
    dataElements: ['真实 Cookie 值', 'Cookie 名称', '域名', '路径', '安全与同站标记', '到期时间'],
    sources: ['登录状态下的扩展固定同步域名清单'],
    purposes: ['让 HOLA DAY 任务浏览器继承 Chrome 中已有的登录状态'],
    sensitivity: 'highly_sensitive',
    storageLocations: ['HOLA DAY 待注入 Cookie 存储', 'HOLA DAY 任务浏览器执行环境'],
    processorIds: ['holaday_internal'],
    retentionPolicyId: 'cookie_injection_mixed',
    rightsCapabilityId: 'extension_cookie_mixed',
    evidence: [
      source(
        'apps/extension/src/background/cookie-sync.ts',
        '扩展读取固定同步域名清单内的 Cookie。',
      ),
      source(
        'apps/orchestrator/src/cookies/sync-service.ts',
        'Cookie 同步服务验证并处理同步记录。',
      ),
      source(
        'apps/orchestrator/src/db/schema/pending-cookies.ts',
        '待注入 Cookie 记录由专用表定义。',
      ),
    ],
  },
  {
    id: 'payments_entitlements',
    displayName: '支付与套餐',
    description: '用于结算、发放权益、退款和处理争议的交易资料。',
    dataElements: ['订单', '金额', '币种', '购买内容', '状态', '渠道标识', '可能的付款邮箱'],
    sources: ['用户选择的支付渠道', '支付结果与权益发放流程'],
    purposes: ['结算、发放权益、退款和处理争议'],
    sensitivity: 'highly_sensitive',
    storageLocations: ['HOLA DAY 支付订单与权益存储'],
    processorIds: ['holaday_internal', 'paypal', 'china_payment'],
    retentionPolicyId: 'transaction_restricted',
    rightsCapabilityId: 'payment_restricted_request',
    evidence: [
      source('apps/orchestrator/src/db/schema/payments.ts', '支付订单由 payments 表定义。'),
      source('apps/orchestrator/src/payment/paypal.ts', 'PayPal 支付流程处理订单状态。'),
      source('apps/orchestrator/src/trpc/routers/payment.ts', '支付路由处理支付与权益流程。'),
    ],
  },
  {
    id: 'partner_kyc_ledger',
    displayName: '合伙人 KYC 与账本',
    description: '用于合伙人资格、账务、出款、风险审核与争议处理的受限资料。',
    dataElements: [
      '银行账户或银行卡指纹',
      'KYC 状态、认证服务商与参考号',
      '提现金额、状态与风险评分',
      '邀请关系与奖励',
      'HOLA Credit 与 API Units 账本及活动记录',
    ],
    sources: ['合伙人认证与账务流程', '充值、分润、提现与风险审核流程'],
    purposes: ['验证合伙人资格与同名账户，处理充值、分润、提现、风险审核、对账与争议'],
    sensitivity: 'highly_sensitive',
    storageLocations: ['HOLA DAY 合伙人资格与账本存储'],
    processorIds: ['holaday_internal', 'china_payment'],
    retentionPolicyId: 'partner_financial_restricted',
    rightsCapabilityId: 'partner_restricted_request',
    evidence: [
      source('apps/orchestrator/src/db/schema/partner.ts', '合伙人资料与账务记录由专用表定义。'),
      source('apps/orchestrator/src/partner/kyc-service.ts', 'KYC 服务处理合伙人认证状态。'),
      source('apps/orchestrator/src/partner/withdrawal-service.ts', '提现服务处理合伙人出款记录。'),
    ],
  },
  {
    id: 'media_assets',
    displayName: '媒体素材',
    description: '为完成明确请求的图片、视频或语音任务而处理的媒体素材。',
    dataElements: ['上传的图片、视频、语音', '声音克隆标识', '授权时间'],
    sources: ['用户上传媒体素材', '用户明确请求的媒体任务'],
    purposes: ['完成您明确请求的图片、视频或语音任务'],
    sensitivity: 'sensitive',
    storageLocations: ['HOLA DAY 任务文件存储', 'HOLA DAY 媒体任务处理存储'],
    processorIds: ['holaday_internal', 'google', 'dashscope', 'fal_ai', 'cloudflare_r2'],
    retentionPolicyId: 'media_mixed',
    rightsCapabilityId: 'media_mixed_control',
    evidence: [
      source('apps/orchestrator/src/db/schema/task-files.ts', '任务文件记录媒体素材。'),
      source(
        'apps/orchestrator/src/agent/image/gemini-image-client.ts',
        'Gemini 图像客户端处理图片任务。',
      ),
      source(
        'apps/orchestrator/src/agent/video/qwen-voice-clone-client.ts',
        'Qwen 客户端处理声音克隆任务。',
      ),
      source(
        'apps/orchestrator/src/agent/video/fal-lipsync-client.ts',
        'fal.ai 客户端处理口型同步任务。',
      ),
      source(
        'apps/orchestrator/src/trpc/routers/video-onboarding.ts',
        '视频引导路由处理媒体授权流程。',
      ),
    ],
  },
  {
    id: 'analytics_logs',
    displayName: '分析与日志',
    description: '用于保障安全与稳定、排查故障并改进体验的运行资料。',
    dataElements: ['固定事件聚合', '匿名摘要', 'IP', 'User-Agent', '操作与错误日志'],
    sources: ['系统运行事件与错误处理'],
    purposes: ['保障安全与稳定、排查故障并改进体验'],
    sensitivity: 'sensitive',
    storageLocations: ['HOLA DAY 分析与运行日志存储'],
    processorIds: ['holaday_internal', 'vultr', 'aliyun'],
    retentionPolicyId: 'analytics_configured_mixed',
    rightsCapabilityId: 'analytics_manual_request',
    evidence: [
      source('apps/orchestrator/src/db/schema/energy-analytics.ts', '能量分析事件由专用表定义。'),
      source(
        'apps/orchestrator/src/config/env.energy-analytics.test.ts',
        '分析配置测试覆盖能量分析开关边界。',
      ),
      source('apps/orchestrator/src/energy/analytics-cleanup.ts', '分析清理服务处理过期分析记录。'),
    ],
  },
];
